/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces/$spaceId/index'
import { Route as SpacesSpaceIdLogsRouteImport } from './routes/spaces/$spaceId/logs'
import { Route as SpacesSpaceIdConfigRouteImport } from './routes/spaces/$spaceId/config'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/spaces/$spaceId/',
  path: '/spaces/$spaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdLogsRoute = SpacesSpaceIdLogsRouteImport.update({
  id: '/spaces/$spaceId/logs',
  path: '/spaces/$spaceId/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdConfigRoute = SpacesSpaceIdConfigRouteImport.update({
  id: '/spaces/$spaceId/config',
  path: '/spaces/$spaceId/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$spaceId/config': typeof SpacesSpaceIdConfigRoute
  '/spaces/$spaceId/logs': typeof SpacesSpaceIdLogsRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/spaces': typeof SpacesIndexRoute
  '/spaces/$spaceId/config': typeof SpacesSpaceIdConfigRoute
  '/spaces/$spaceId/logs': typeof SpacesSpaceIdLogsRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/terminal': typeof TerminalRoute
  '/spaces/': typeof SpacesIndexRoute
  '/spaces/$spaceId/config': typeof SpacesSpaceIdConfigRoute
  '/spaces/$spaceId/logs': typeof SpacesSpaceIdLogsRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/terminal'
    | '/spaces/'
    | '/spaces/$spaceId/config'
    | '/spaces/$spaceId/logs'
    | '/spaces/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/terminal'
    | '/spaces'
    | '/spaces/$spaceId/config'
    | '/spaces/$spaceId/logs'
    | '/spaces/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/terminal'
    | '/spaces/'
    | '/spaces/$spaceId/config'
    | '/spaces/$spaceId/logs'
    | '/spaces/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TerminalRoute: typeof TerminalRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  SpacesSpaceIdConfigRoute: typeof SpacesSpaceIdConfigRoute
  SpacesSpaceIdLogsRoute: typeof SpacesSpaceIdLogsRoute
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/logs': {
      id: '/spaces/$spaceId/logs'
      path: '/spaces/$spaceId/logs'
      fullPath: '/spaces/$spaceId/logs'
      preLoaderRoute: typeof SpacesSpaceIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/config': {
      id: '/spaces/$spaceId/config'
      path: '/spaces/$spaceId/config'
      fullPath: '/spaces/$spaceId/config'
      preLoaderRoute: typeof SpacesSpaceIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TerminalRoute: TerminalRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  SpacesSpaceIdConfigRoute: SpacesSpaceIdConfigRoute,
  SpacesSpaceIdLogsRoute: SpacesSpaceIdLogsRoute,
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
