import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFile, mkdir, mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { bootstrapProfile } from '../src/profile-bootstrap.js'

const here = dirname(fileURLToPath(import.meta.url))
// The real dsh workspace root — this is an integration test (matching this
// track's established convention of running the real assemble script rather
// than mocking it; see e.g. space-format's diff-harness tests).
const dshRoot = join(here, '..', '..', '..')

test('bootstrapProfile: writes a link-only profile package.json (Part A3 shape) when none exists', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  try {
    await bootstrapProfile({ dshRoot, dshHome })
    const pkg = JSON.parse(await readFile(join(dshHome, 'profiles', 'lmthing-web', 'package.json'), 'utf8'))
    assert.deepEqual(Object.keys(pkg.dependencies), [
      '@lmthing/dsh-llm-mock',
      '@lmthing/dsh-space',
      '@lmthing/dsh-subagent-preset',
      '@lmthing/dsh-client-space-components',
      '@lmthing/dsh-default-workspace',
      '@lmthing/dsh-client-brand',
    ])
    // The Part A3 fix this must never regress: no direct @deepseek-ai/dsh-web-app dep.
    assert.ok(!('@deepseek-ai/dsh-web-app' in pkg.dependencies))
    assert.deepEqual(pkg.dsh.profile.bundles, ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app'])
  } finally {
    await rm(dshHome, { recursive: true, force: true })
  }
})

test('bootstrapProfile: is idempotent — a second run does not overwrite a pre-existing profile package.json', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  try {
    await bootstrapProfile({ dshRoot, dshHome })
    const pkgPath = join(dshHome, 'profiles', 'lmthing-web', 'package.json')
    const before = await readFile(pkgPath, 'utf8')
    await bootstrapProfile({ dshRoot, dshHome })
    const after = await readFile(pkgPath, 'utf8')
    assert.equal(before, after)
  } finally {
    await rm(dshHome, { recursive: true, force: true })
  }
})

test('bootstrapProfile: regenerates cordis.patch.yml and the agent-presets roster (delegates to assemble-lmthing-profile.mjs)', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  try {
    await bootstrapProfile({ dshRoot, dshHome })
    const patch = await readFile(join(dshHome, 'profiles', 'lmthing-web', 'cordis.patch.yml'), 'utf8')
    assert.match(patch, /GENERATED by dsh\/scripts\/assemble-lmthing-profile\.mjs/)
    const rosterEntries = await readFile(join(dshHome, '.agent-presets', 'thing', 'agent.cordis.yml'), 'utf8')
    assert.match(rosterEntries, /lmthing-space/)
  } finally {
    await rm(dshHome, { recursive: true, force: true })
  }
})

test('bootstrapProfile: with no LMTHINGCLOUD_BASE_URL set, generates no production model patch', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  const original = process.env.LMTHINGCLOUD_BASE_URL
  delete process.env.LMTHINGCLOUD_BASE_URL
  try {
    const { patchPaths } = await bootstrapProfile({ dshRoot, dshHome })
    assert.deepEqual(patchPaths, [])
  } finally {
    if (original !== undefined) process.env.LMTHINGCLOUD_BASE_URL = original
    await rm(dshHome, { recursive: true, force: true })
  }
})

test('bootstrapProfile: when an image-baked profile exists, copies it and re-links @lmthing/* symlinks against THIS boot\'s dshRoot (never runs pnpm)', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  const profileBaseDir = join(dshRoot, '.profile-base')
  const bakedProfileDir = join(profileBaseDir, 'lmthing-web')
  try {
    // Fabricate a minimal "baked at build time" profile — including a deliberately-wrong
    // relative symlink of the exact shape pnpm's `link:` protocol would actually produce at
    // THIS depth (.profile-base/lmthing-web/node_modules/@lmthing/ -> ../../../../packages/space
    // resolves to dshRoot/packages/space from HERE, but would resolve to a nonexistent
    // dshHome/packages/space if copied verbatim and never re-linked).
    const bakedLinkDir = join(bakedProfileDir, 'node_modules', '@lmthing')
    await mkdir(bakedLinkDir, { recursive: true })
    await writeFile(join(bakedProfileDir, 'package.json'), '{"name":"dsh-profile-lmthing-web-baked-fixture"}\n', 'utf8')
    await symlink('../../../../packages/space', join(bakedLinkDir, 'dsh-space'), 'dir')

    await bootstrapProfile({ dshRoot, dshHome })

    const linkPath = join(dshHome, 'profiles', 'lmthing-web', 'node_modules', '@lmthing', 'dsh-space')
    assert.equal(await realpath(linkPath), await realpath(join(dshRoot, 'packages', 'space')))
  } finally {
    // Remove the whole fabricated .profile-base/, not just lmthing-web/ under it — otherwise an
    // empty .profile-base/ directory is left behind in the real checkout.
    await rm(profileBaseDir, { recursive: true, force: true })
    await rm(dshHome, { recursive: true, force: true })
  }
})

test('bootstrapProfile: with LMTHINGCLOUD_BASE_URL set, writes a real-provider patch naming the LiteLLM route (never the raw key)', async () => {
  const dshHome = await mkdtemp(join(tmpdir(), 'dsh-pod-server-test-'))
  const originalUrl = process.env.LMTHINGCLOUD_BASE_URL
  const originalKey = process.env.LMTHINGCLOUD_API_KEY
  process.env.LMTHINGCLOUD_BASE_URL = 'http://litellm.lmthing.svc.cluster.local:4000/v1'
  process.env.LMTHINGCLOUD_API_KEY = 'sk-super-secret-value'
  try {
    const { patchPaths } = await bootstrapProfile({ dshRoot, dshHome, model: 'DeepSeek-V4-Flash-0731' })
    assert.equal(patchPaths.length, 1)
    const patch = await readFile(patchPaths[0], 'utf8')
    assert.match(patch, /baseURL: http:\/\/litellm\.lmthing\.svc\.cluster\.local:4000\/v1/)
    assert.match(patch, /apiKeyEnv: LMTHINGCLOUD_API_KEY/)
    assert.match(patch, /provider: lmthingcloud/)
    assert.match(patch, /model: DeepSeek-V4-Flash-0731/)
    // The credential VALUE must never be written to disk — only the env var's NAME.
    assert.ok(!patch.includes('sk-super-secret-value'))
  } finally {
    if (originalUrl !== undefined) process.env.LMTHINGCLOUD_BASE_URL = originalUrl
    else delete process.env.LMTHINGCLOUD_BASE_URL
    if (originalKey !== undefined) process.env.LMTHINGCLOUD_API_KEY = originalKey
    else delete process.env.LMTHINGCLOUD_API_KEY
    await rm(dshHome, { recursive: true, force: true })
  }
})
