import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { stringify } from 'yaml'

/**
 * Generate one `@deepseek-ai/dsh-agent-presets` roster directory — one preset per agent, each
 * mounting exactly `@lmthing/dsh-space { spaceDir, agentSlug, registry }` (with `mountPersona`
 * left at its default `true`, since a preset IS a real agent-preset scope — the `mountPersona:
 * false` global-persona hack `scripts/assemble-lmthing-profile.mjs` needs for the top-level
 * headless agent is no longer needed for anything mounted through this roster).
 *
 * Part A2 (see dsh/PROGRESS.md): this is the roster that makes per-agent capability isolation
 * possible at all. Each generated preset is a REAL, independent standing composition —
 * `@lmthing/dsh-subagent-preset`'s `recompose()`-based provider joins a delegated child to
 * exactly the target's own preset here, not the union of parent + target tools.
 *
 * `registry` MUST be included in every generated preset's config — a real bug this port hit and
 * fixed: without it, `@lmthing/dsh-space-delegate` (mounted by `@lmthing/dsh-space` inside each
 * preset) receives an empty registry, resolves zero delegation targets, and silently mounts no
 * `delegate_*` tool at all. No thrown error anywhere — the agent just quietly can't delegate.
 *
 * @param {string} rosterDir - absolute path to the roster root (each agent gets `<rosterDir>/<slug>/agent.cordis.yml`).
 * @param {Record<string, { spaceDir: string, agentSlug: string }>} agents - slug -> where that agent's space lives.
 * @param {Record<string, { agent: object, spaceDir: string }>} [registry] - every delegatable agent, keyed by slug (same shape `@lmthing/dsh-space-delegate` expects). Defaults to `{}` — an agents-only-no-delegation roster.
 * @returns {Promise<void>}
 */
export async function generatePresetRoster(rosterDir, agents, registry = {}) {
  for (const [slug, { spaceDir, agentSlug }] of Object.entries(agents)) {
    const presetDir = join(rosterDir, slug)
    await mkdir(presetDir, { recursive: true })
    const composition = [
      {
        id: 'lmthing-space',
        name: '@lmthing/dsh-space',
        config: { spaceDir, agentSlug, registry },
      },
    ]
    const header = `# GENERATED by @lmthing/dsh-preset-roster for agent "${slug}" — re-run the assembler to regenerate.\n`
    await writeFile(join(presetDir, 'agent.cordis.yml'), header + stringify(composition), 'utf8')
  }
}
