packages:
  - blog
  - studio
  - casa
  - chat
  - com
  - computer
  - space
  - social
  - store
  - team
  - cloud
  - org/libs/*

overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
