---
- name: Deploy lmthing cloud services
  hosts: kube_control_plane[0]
  become: true
  gather_facts: true
  vars_files:
    - ../vault.yml
  roles:
    - role: envoy_gateway
      tags: [infra, envoy]
    - role: buildkit
      tags: [infra, buildkit, images]
    - role: argocd
      tags: [infra, argocd]
    - role: cloud_build_images
      tags: [images]
    - role: cloud_secrets
      tags: [secrets]
    - role: argocd_apps
      tags: [argocd, apps]
    - role: ingress_iptables
      tags: [infra, ingress]
