---
- name: Deploy lmthing cloud services
  hosts: kube_control_plane[0]
  become: true
  gather_facts: true
  vars_files:
    - ../vault.yml
  roles:
    - role: envoy_gateway
      tags: [infra, envoy]
    - role: buildkit
      tags: [infra, buildkit, images]
    - role: cloud_build_images
      tags: [images]
    - role: cloud_apply_manifests
      tags: [manifests]
    - role: cloud_compute
      tags: [compute]
    - role: ingress_iptables
      tags: [infra, ingress]
