/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdIndexRouteImport } from './routes/room/$roomId/index'
import { Route as RoomRoomIdSettingsRouteImport } from './routes/room/$roomId/settings'
import { Route as RoomRoomIdMembersRouteImport } from './routes/room/$roomId/members'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdIndexRoute = RoomRoomIdIndexRouteImport.update({
  id: '/room/$roomId/',
  path: '/room/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdSettingsRoute = RoomRoomIdSettingsRouteImport.update({
  id: '/room/$roomId/settings',
  path: '/room/$roomId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdMembersRoute = RoomRoomIdMembersRouteImport.update({
  id: '/room/$roomId/members',
  path: '/room/$roomId/members',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/room/$roomId/members': typeof RoomRoomIdMembersRoute
  '/room/$roomId/settings': typeof RoomRoomIdSettingsRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/room/$roomId/members': typeof RoomRoomIdMembersRoute
  '/room/$roomId/settings': typeof RoomRoomIdSettingsRoute
  '/room/$roomId': typeof RoomRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/room/$roomId/members': typeof RoomRoomIdMembersRoute
  '/room/$roomId/settings': typeof RoomRoomIdSettingsRoute
  '/room/$roomId/': typeof RoomRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/room/$roomId/members'
    | '/room/$roomId/settings'
    | '/room/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/room/$roomId/members'
    | '/room/$roomId/settings'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/room/$roomId/members'
    | '/room/$roomId/settings'
    | '/room/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  RoomRoomIdMembersRoute: typeof RoomRoomIdMembersRoute
  RoomRoomIdSettingsRoute: typeof RoomRoomIdSettingsRoute
  RoomRoomIdIndexRoute: typeof RoomRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/': {
      id: '/room/$roomId/'
      path: '/room/$roomId'
      fullPath: '/room/$roomId/'
      preLoaderRoute: typeof RoomRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/settings': {
      id: '/room/$roomId/settings'
      path: '/room/$roomId/settings'
      fullPath: '/room/$roomId/settings'
      preLoaderRoute: typeof RoomRoomIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId/members': {
      id: '/room/$roomId/members'
      path: '/room/$roomId/members'
      fullPath: '/room/$roomId/members'
      preLoaderRoute: typeof RoomRoomIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  RoomRoomIdMembersRoute: RoomRoomIdMembersRoute,
  RoomRoomIdSettingsRoute: RoomRoomIdSettingsRoute,
  RoomRoomIdIndexRoute: RoomRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
