type Row = Record<string, unknown>;
interface AsyncDb {
  query(table: string, opts?: { where?: Record<string, unknown> }): Promise<Row[]>;
  insert(table: string, values: Row | Row[]): Promise<Row | Row[]>;
  update(table: string, opts: { where: Record<string, unknown>; set: Record<string, unknown> }): Promise<number>;
}

interface Medication {
  id: string;
  endedAt?: string | null;
  reminderTime?: string | null; // 'HH:MM', null = no daily reminder configured
}

interface AdherenceLog {
  id: string;
  medicationId: string;
  scheduledAt: string;
  status: string;
}

// Imperative cron handler — NO agent, NO LLM. This used to delegate to
// `pharmacy/pharmacist#reminders`, an agent action that only ever READ
// medications/adherence_logs and `display()`-ed a plain-language summary; it
// never wrote to the database (see spaces/pharmacy/agents/pharmacist/instruct.md,
// "Action: reminders"). That's pure date/threshold arithmetic — a wasted agent
// episode. This handler reproduces it as deterministic code and does the one
// piece of real work the agent could never do headlessly: it actually
// materializes today's expected dose for every medication with a configured
// `reminderTime` (as a 'pending' or already-'missed' adherence_logs row, so the
// existing Doses page / "Needs attention" strip — which already read
// `adherence_logs` live — have something to show), and reconciles any
// still-`pending` row whose scheduled time has passed to `'missed'`.
//
// Idempotent: at most one adherence_logs row is inserted per medication per
// calendar day (skipped if one already exists, however it got there — manually
// logged or previously generated by this same hook), and the missed-reconcile
// only touches rows still `'pending'`, so re-running the same day is a no-op
// past the first pass.
export default {
  type: 'cron',
  daily: '09:00',
  budget: { maxWallClockMs: 60000 },
  handler: async ({ db }: { db: AsyncDb }) => {
    const now = new Date();
    const todayStr = now.toISOString().slice(0, 10); // 'YYYY-MM-DD'

    const medications = (await db.query('medications', {})) as Medication[];
    const active = medications.filter((m) => !m.endedAt && m.reminderTime);

    for (const med of active) {
      // `where` is equality-only, so pull this medication's logs and check for
      // today's date in memory rather than a range query.
      const logs = (await db.query('adherence_logs', {
        where: { medicationId: med.id },
      })) as AdherenceLog[];
      const hasToday = logs.some((l) => String(l.scheduledAt).slice(0, 10) === todayStr);
      if (hasToday) continue; // already logged (manually or by an earlier run) — skip

      const scheduledAt = `${todayStr}T${med.reminderTime}:00.000Z`;
      const status = new Date(scheduledAt) <= now ? 'missed' : 'pending';
      await db.insert('adherence_logs', { medicationId: med.id, scheduledAt, status });
    }

    // Reconcile: any dose still `pending` whose scheduled time has since passed
    // (from an earlier run today, or an un-resolved prior day) is now missed.
    const stillPending = (await db.query('adherence_logs', {
      where: { status: 'pending' },
    })) as AdherenceLog[];
    for (const log of stillPending) {
      if (new Date(log.scheduledAt) <= now) {
        await db.update('adherence_logs', { where: { id: log.id }, set: { status: 'missed' } });
      }
    }
  },
};
