apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - zitadel.yaml
  - litellm.yaml
  - render.yaml
  - gateway.yaml
  - computer.yaml
  - compute-pod-template.yaml
  - compute-prepull.yaml
  - studio.yaml
  - chat.yaml
  - com.yaml
  - social.yaml
  - store.yaml
  - org.yaml
  - space.yaml
  - team.yaml
  - blog.yaml
  - casa.yaml
