apiVersion: apps/v1
kind: Deployment
metadata:
  name: social
  namespace: lmthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      imagePullSecrets:
        - name: acr-pull-secret
      containers:
        - name: social
          image: lmthingacr.azurecr.io/social:e15285b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: social
  namespace: lmthing
spec:
  selector:
    app: social
  ports:
    - port: 80
      targetPort: 80
