/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ExploreExplorationIdRouteImport } from './routes/explore/$explorationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreExplorationIdRoute = ExploreExplorationIdRouteImport.update({
  id: '/explore/$explorationId',
  path: '/explore/$explorationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore/$explorationId': typeof ExploreExplorationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore/$explorationId': typeof ExploreExplorationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/explore': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore/$explorationId': typeof ExploreExplorationIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore/$explorationId'
    | '/profile/$username'
    | '/explore/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explore/$explorationId' | '/profile/$username' | '/explore'
  id:
    | '__root__'
    | '/'
    | '/explore/$explorationId'
    | '/profile/$username'
    | '/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreExplorationIdRoute: typeof ExploreExplorationIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$explorationId': {
      id: '/explore/$explorationId'
      path: '/explore/$explorationId'
      fullPath: '/explore/$explorationId'
      preLoaderRoute: typeof ExploreExplorationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreExplorationIdRoute: ExploreExplorationIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ExploreIndexRoute: ExploreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
