/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpaceIdIndexRouteImport } from './routes/$spaceId/index'
import { Route as SpaceIdTerminalRouteImport } from './routes/$spaceId/terminal'
import { Route as SpaceIdSettingsRouteImport } from './routes/$spaceId/settings'
import { Route as SpaceIdLogsRouteImport } from './routes/$spaceId/logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdIndexRoute = SpaceIdIndexRouteImport.update({
  id: '/$spaceId/',
  path: '/$spaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdTerminalRoute = SpaceIdTerminalRouteImport.update({
  id: '/$spaceId/terminal',
  path: '/$spaceId/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdSettingsRoute = SpaceIdSettingsRouteImport.update({
  id: '/$spaceId/settings',
  path: '/$spaceId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceIdLogsRoute = SpaceIdLogsRouteImport.update({
  id: '/$spaceId/logs',
  path: '/$spaceId/logs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$spaceId/logs': typeof SpaceIdLogsRoute
  '/$spaceId/settings': typeof SpaceIdSettingsRoute
  '/$spaceId/terminal': typeof SpaceIdTerminalRoute
  '/$spaceId/': typeof SpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$spaceId/logs': typeof SpaceIdLogsRoute
  '/$spaceId/settings': typeof SpaceIdSettingsRoute
  '/$spaceId/terminal': typeof SpaceIdTerminalRoute
  '/$spaceId': typeof SpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$spaceId/logs': typeof SpaceIdLogsRoute
  '/$spaceId/settings': typeof SpaceIdSettingsRoute
  '/$spaceId/terminal': typeof SpaceIdTerminalRoute
  '/$spaceId/': typeof SpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$spaceId/logs'
    | '/$spaceId/settings'
    | '/$spaceId/terminal'
    | '/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$spaceId/logs'
    | '/$spaceId/settings'
    | '/$spaceId/terminal'
    | '/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/$spaceId/logs'
    | '/$spaceId/settings'
    | '/$spaceId/terminal'
    | '/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpaceIdLogsRoute: typeof SpaceIdLogsRoute
  SpaceIdSettingsRoute: typeof SpaceIdSettingsRoute
  SpaceIdTerminalRoute: typeof SpaceIdTerminalRoute
  SpaceIdIndexRoute: typeof SpaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceId/': {
      id: '/$spaceId/'
      path: '/$spaceId'
      fullPath: '/$spaceId/'
      preLoaderRoute: typeof SpaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceId/terminal': {
      id: '/$spaceId/terminal'
      path: '/$spaceId/terminal'
      fullPath: '/$spaceId/terminal'
      preLoaderRoute: typeof SpaceIdTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceId/settings': {
      id: '/$spaceId/settings'
      path: '/$spaceId/settings'
      fullPath: '/$spaceId/settings'
      preLoaderRoute: typeof SpaceIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$spaceId/logs': {
      id: '/$spaceId/logs'
      path: '/$spaceId/logs'
      fullPath: '/$spaceId/logs'
      preLoaderRoute: typeof SpaceIdLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpaceIdLogsRoute: SpaceIdLogsRoute,
  SpaceIdSettingsRoute: SpaceIdSettingsRoute,
  SpaceIdTerminalRoute: SpaceIdTerminalRoute,
  SpaceIdIndexRoute: SpaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
