/**
 * Typed accessor for the store catalog manifest (Phase 10 — store distribution).
 *
 * `store/projects/manifest.json` is generated by `store/scripts/gen-apps-manifest.mjs`
 * (wired into the Vite build in `store/vite.config.ts`) from `store/projects/<appId>/`
 * project-app templates. Imported directly (a plain JSON ES module) rather than
 * fetched, so the catalog browse pages need no network round-trip in dev or prod
 * — Vite inlines it at build time and serves it fresh on every dev-server request.
 */
import manifestData from '../../projects/manifest.json'

/** One `store/projects/<appId>/` catalog entry, as derived by the manifest generator. */
export interface CatalogApp {
  id: string
  title: string
  description: string
  /** Free-form catalog icon (emoji or short glyph) from the app's `project.json`; `null` when unset. */
  icon: string | null
  /** Table names from `database/*.json`. */
  tables: string[]
  /** Page file paths (relative to `pages/`). */
  pages: string[]
  /** Endpoint names — `api/<name>/` directory names. */
  endpoints: string[]
  /** Hook names from `hooks/*.ts`. */
  hooks: string[]
}

/** One `store/spaces/<id>/` catalog entry — a standalone/installable space (e.g. `integration-*`). */
export interface CatalogSpace {
  /** Directory name under `store/spaces/`. */
  id: string
  /** `lmthing.title` from `package.json`, or a humanized fallback of `id`. */
  title: string
  /** `lmthing.description` from `package.json`, or `pkg.description`, or `''`. */
  description: string
  /** Free-form catalog icon (emoji or short glyph) from `lmthing.icon`; `null` when unset. */
  icon: string | null
  /** `lmthing.tags` from `package.json` (e.g. `['integration']`); `[]` when unset. */
  tags: string[]
  /** `lmthing.kind` from `package.json` (e.g. `'integration'`); `null` when unset. */
  kind: string | null
  /** `lmthing.settings` — a JSON Schema describing the space's configurable env vars; `null` when unset. */
  settings: unknown | null
  /** ALL file paths under the space dir, relative to it (`/`-joined, sorted). */
  files: string[]
}

export interface AppsManifest {
  apps: CatalogApp[]
  spaces: CatalogSpace[]
}

export const appsManifest = { spaces: [], ...(manifestData as AppsManifest) } as AppsManifest

/** All published catalog apps. */
export function listCatalogApps(): CatalogApp[] {
  return appsManifest.apps
}

/** One catalog app by id, or `undefined` when not published. */
export function getCatalogApp(appId: string): CatalogApp | undefined {
  return appsManifest.apps.find((app) => app.id === appId)
}

/** All published catalog spaces (standalone/installable spaces, e.g. `integration-*`). */
export function listCatalogSpaces(): CatalogSpace[] {
  return appsManifest.spaces
}

/** Published catalog spaces tagged `integration` — the store-installable integrations. */
export function listCatalogIntegrations(): CatalogSpace[] {
  return appsManifest.spaces.filter((space) => space.tags.includes('integration'))
}

/** One catalog space by id, or `undefined` when not published. */
export function getCatalogSpace(spaceId: string): CatalogSpace | undefined {
  return appsManifest.spaces.find((space) => space.id === spaceId)
}
