/**
 * Typed accessor for the store catalog manifest (Phase 10 — store distribution).
 *
 * `store/projects/manifest.json` is generated by `store/scripts/gen-apps-manifest.mjs`
 * (wired into the Vite build in `store/vite.config.ts`) from `store/projects/<appId>/`
 * project-app templates. Imported directly (a plain JSON ES module) rather than
 * fetched, so the catalog browse pages need no network round-trip in dev or prod
 * — Vite inlines it at build time and serves it fresh on every dev-server request.
 */
import manifestData from '../../projects/manifest.json'

/** One `store/projects/<appId>/` catalog entry, as derived by the manifest generator. */
export interface CatalogApp {
  id: string
  title: string
  description: string
  /** Free-form catalog icon (emoji or short glyph) from the app's `project.json`; `null` when unset. */
  icon: string | null
  /** Table names from `database/*.json`. */
  tables: string[]
  /** Page file paths (relative to `pages/`). */
  pages: string[]
  /** Endpoint names — `api/<name>/` directory names. */
  endpoints: string[]
  /** Hook names from `hooks/*.ts`. */
  hooks: string[]
}

export interface AppsManifest {
  apps: CatalogApp[]
}

export const appsManifest = manifestData as AppsManifest

/** All published catalog apps. */
export function listCatalogApps(): CatalogApp[] {
  return appsManifest.apps
}

/** One catalog app by id, or `undefined` when not published. */
export function getCatalogApp(appId: string): CatalogApp | undefined {
  return appsManifest.apps.find((app) => app.id === appId)
}
