import { join } from 'node:path';
import { createSpace, deleteSpaceFile, validateSpace, writeAgent, writeFunction, writeKnowledge, writeTasklistNode } from '../format/write.ts';
import type { TaskNode } from '../format/types.ts';
import type { ToolDef, ToolGroup } from './ctx.ts';

function string(args: Record<string, unknown>, key: string): string { const value = args[key]; if (typeof value !== 'string' || !value) throw new Error(`${key} must be a non-empty string`); return value; }
async function spaceDir(ctx: Parameters<ToolGroup>[0], id: string): Promise<string> { const space = await ctx.space(id); if (!space) throw new Error(`Unknown space ${id}`); return space.dir; }
const resultSchema = { type: 'object', properties: {}, additionalProperties: true } as const;

export const tools: ToolGroup = (ctx): ToolDef[] => [
  { name: 'create_space', description: 'Create a minimal parseable space with one agent.', inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'], additionalProperties: false }, async handler(args) { const result = await createSpace(ctx.spacesDir, string(args, 'id')); if (result.ok) await ctx.reload(); return result; } },
  { name: 'write_agent', description: 'Write an agent instruct.md and optional charter.md, validating the candidate space before commit.', inputSchema: { type: 'object', properties: { space: { type: 'string' }, slug: { type: 'string' }, frontmatter: resultSchema, instruct: { type: 'string' }, charter: { type: 'string' } }, required: ['space', 'slug', 'frontmatter', 'instruct'], additionalProperties: false }, async handler(args) { const result = await writeAgent(await spaceDir(ctx, string(args, 'space')), string(args, 'slug'), args.frontmatter, string(args, 'instruct'), args.charter === undefined ? undefined : string(args, 'charter')); if (result.ok) await ctx.reload(); return result; } },
  { name: 'write_function', description: 'Write a TypeScript space function, extract its tool schema, and validate the candidate space.', inputSchema: { type: 'object', properties: { space: { type: 'string' }, name: { type: 'string' }, source: { type: 'string' } }, required: ['space', 'name', 'source'], additionalProperties: false }, async handler(args) { const result = await writeFunction(await spaceDir(ctx, string(args, 'space')), string(args, 'name'), string(args, 'source')); if (result.ok) await ctx.reload(); return result; } },
  { name: 'write_knowledge', description: 'Write one knowledge aspect and re-parse the complete candidate space before commit.', inputSchema: { type: 'object', properties: { space: { type: 'string' }, domain: { type: 'string' }, field: { type: 'string' }, option: { type: 'string' }, body: { type: 'string' } }, required: ['space', 'domain', 'field', 'option', 'body'], additionalProperties: false }, async handler(args) { const result = await writeKnowledge(await spaceDir(ctx, string(args, 'space')), string(args, 'domain'), string(args, 'field'), string(args, 'option'), string(args, 'body')); if (result.ok) await ctx.reload(); return result; } },
  { name: 'write_tasklist_node', description: 'Write an agent tasklist markdown node and reject unknown dependencies or cycles.', inputSchema: { type: 'object', properties: { space: { type: 'string' }, slug: { type: 'string' }, id: { type: 'string' }, node: resultSchema }, required: ['space', 'slug', 'id', 'node'], additionalProperties: false }, async handler(args) { const raw = args.node; if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new Error('node must be an object'); const node = raw as Omit<TaskNode, 'file' | 'id'>; const result = await writeTasklistNode(await spaceDir(ctx, string(args, 'space')), string(args, 'slug'), string(args, 'id'), node); if (result.ok) await ctx.reload(); return result; } },
  { name: 'delete_space_file', description: 'Delete one regular in-space file only if the resulting space still parses.', inputSchema: { type: 'object', properties: { space: { type: 'string' }, path: { type: 'string' } }, required: ['space', 'path'], additionalProperties: false }, async handler(args) { const result = await deleteSpaceFile(await spaceDir(ctx, string(args, 'space')), string(args, 'path')); if (result.ok) await ctx.reload(); return result; } },
  { name: 'validate_space', description: 'Re-parse a space and return all format problems rather than only the first.', inputSchema: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'], additionalProperties: false }, async handler(args) { return validateSpace(await spaceDir(ctx, string(args, 'id'))); } },
];
