apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmthing-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lmthing/lmthing.git
    targetRevision: main
    path: devops/argocd/core
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
