apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lmthing

resources:
  - litellm.yaml
  - gateway.yaml
  - computer.yaml

secretGenerator:
  - name: lmthing-secrets
    envs:
      - .env.secrets
    options:
      disableNameSuffixHash: true
