/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsAppIdRouteImport } from './routes/projects/$appId'
import { Route as CategoryCategoryIdRouteImport } from './routes/category/$categoryId'
import { Route as AgentAgentIdRouteImport } from './routes/agent/$agentId'

const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsAppIdRoute = ProjectsAppIdRouteImport.update({
  id: '/projects/$appId',
  path: '/projects/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/publish': typeof PublishRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/projects/$appId': typeof ProjectsAppIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/publish': typeof PublishRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/projects/$appId': typeof ProjectsAppIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/publish': typeof PublishRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/projects/$appId': typeof ProjectsAppIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/publish'
    | '/agent/$agentId'
    | '/category/$categoryId'
    | '/projects/$appId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/publish'
    | '/agent/$agentId'
    | '/category/$categoryId'
    | '/projects/$appId'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/publish'
    | '/agent/$agentId'
    | '/category/$categoryId'
    | '/projects/$appId'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublishRoute: typeof PublishRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  ProjectsAppIdRoute: typeof ProjectsAppIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$appId': {
      id: '/projects/$appId'
      path: '/projects/$appId'
      fullPath: '/projects/$appId'
      preLoaderRoute: typeof ProjectsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublishRoute: PublishRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  ProjectsAppIdRoute: ProjectsAppIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
