name: Trigger team deploy

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    name: Dispatch to lmthing/team
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: lmthing/team
          event-type: deploy-team
